### ISSUE TITLE
Use PullIfNotPresent for images that have a digest?

### ISSUE THREAD

**Issue by dziemba** [buildkite/agent-stack-k8s#415]
Follow-up to: https://github.com/buildkite/agent-stack-k8s/issues/411

In the init-container logic https://github.com/buildkite/agent-stack-k8s/blob/00a778db02818843253416d6833ff0199d8ea13c/internal/controller/scheduler/scheduler.go#L510 we use `PullAlways` to ensure the images are present. Pulling an image that already exists takes ~1s in our clusters, which adds up quickly when using many containers. 

We could optimize this further by using `PullIfNotPresent` instead `PullAlways` for any images that contain a digest, e.g. `ghcr.io/buildkite/agent@sha256:17fbf3e3d5574ba4dc6e7436391635b0a4a4a7f78a751a372e2456d2d72f541d`. Since the exact version is pinned by the hash, we don't need to pull if the image is present since it's guaranteed that we already have the correct version.

This would change the observed behavior slightly in the case where the image doesn't exist in the upstream registry anymore. Instead of failing consistently, any nodes that have the image cached would keep using it.

(Feel free to reject this idea, it might not be worth the extra complexity.)

**Comment by artem-zinnatullin** [comment]
Oh… Finally I understand why our jobs started to fail with imagepull errors after switching to this Operator from https://github.com/EmbarkStudios/k8s-buildkite-plugin

Just today we had master branch build failure due to `The following container images couldn't be pulled: xxx` on our regular image that is for sure in AWS ECR but apparently ECR sometimes responds worse under this increased load because previous K8S integration used `PullIfNotPresent` and hit node cache.

I think `imagePullPolicy` should definitely be configurable on user level for all images involved in the K8S job, it's on users to guarantee they don't overwrite CI image tags and if they do then use they should use `Always` policy.

Let's at least make it configurable, maybe keep the current behavior for compatibility and gradually announce a change to default if needed.

**Comment by calvinbui** [comment]
> I think `imagePullPolicy` should definitely be configurable on user level

afaik it is configurable by editing the pod-spec-patch so that each initContainer/container is listed along with its imagePullPolicy

**Comment by DrJosh9000** [comment]
@dziemba wrote:
> We could optimize this further by using PullIfNotPresent instead PullAlways for any images that contain a digest, e.g. ghcr.io/buildkite/agent@sha256:17fbf3e3d5574ba4dc6e7436391635b0a4a4a7f78a751a372e2456d2d72f541d. Since the exact version is pinned by the hash, we don't need to pull if the image is present since it's guaranteed that we already have the correct version.

Thanks for the continued thinking on this @dziemba! I like this idea, and it should be easy and safe enough to do. That said, I won't make promises when it will happen. Would someone wish to raise a PR?

@artem-zinnatullin wrote:
> I think imagePullPolicy should definitely be configurable on user level for all images involved in the K8S job, it's on users to guarantee they don't overwrite CI image tags and if they do then use they should use Always policy.

Thanks @artem-zinnatullin - I think @calvinbui is correct about pod-spec-patch offering a workaround here, but I also agree that there could be an easier way to configure a default for all image pulls (for the controller or per step via the plugin). Using pod-spec-patch may be brittle if the names and numbers of each container changes. A separate config would handle it.
